name: Ruby

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        container_tag:
        - "2.7"
        - "3.0"
        - "3.1"
        - "master-nightly-focal"
        task:
        - test
        - test:output
        - build
    container:
      image: rubylang/ruby:${{ matrix.container_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Run test
      run: |
        ruby -v
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/setup
        bundle exec rake ${{matrix.task}}
